[tools]
node = "24"

[hooks]
postinstall = "npx corepack enable"

[settings]
experimental = true

[tasks]
"test:ci" = "pnpm test:ci"
install = "pnpm install"
build = "pnpm build"
dev = "pnpm dev"
test = "pnpm test"
oxlint = "pnpm oxlint"
oxfmt = "pnpm oxfmt --check"

