[tools]
node = "24"

[hooks]
postinstall = "npx corepack enable"

[settings]
experimental = true

[tasks]
install = "pnpm install"
build = "pnpm build && pnpm typecheck"
dev = "pnpm dev"
test = "pnpm test"
oxlint = "pnpm oxlint"
oxfmt = "pnpm oxfmt --check"
