on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [oxlint, oxfmt, build, test]
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: mise run install --frozen-lockfile

      - name: Install Playwright Browsers
        if: matrix.task == 'test'
        run: pnpm exec playwright install --with-deps chromium
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 0

      - run: mise run ${{ matrix.task }}

      - name: Upload coverage artifacts
        if: matrix.task == 'test'
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
